controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    slider_position_controller:
      type: position_controllers/JointPositionController

    arm_position_controller:
      type: position_controllers/JointPositionController

slider_position_controller:
  ros__parameters:
    joint: slider_joint
    interface_name: position

arm_position_controller:
  ros__parameters:
    joint: arm_joint
    interface_name: position
